# Generated by Django 3.0.6 on 2020-05-28 22:54

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(null=True, upload_to=forum.models.thread_path),
        ),
    ]
